### PR TITLE
Updated version of ShowCaseView

### PR DESCRIPTION
**Pull request by JJSWART**
The following features were added to accommodate one of my projects. 
- Set background color of showcase. 
- Set background color of message box
- Set title text color
- Set content text color
- Make showcase a circle or rectangle
- Added a previous and next arrow with a onclick listener. - Use the setArrowsClicked method. 
- Set Arrows to Show and Hide the arrows. 
- Set corner radius of rectangle. 
- Function to remove all tap dismiss events.
- This enable custom events and arrows.
- Add setClickable - false - no touch registered. Else touch registered and onDismiss can be called as default. 

All defaults are set to existing defaults. Except the isClickable which is default false. The targetView click default is great but if you need the library to work in an app where you maybe utilize custom swipe events or click events it can be a problem. 

- TODO - change arrow position constructor/method to be added. Time constraint at the moment.

### CODE REVIEW

**Comment by mreram** [comment]
Dear JJSWART,
It's not fair to apply a few changes to your code, but it's best to check them out and send a pull request.

**Comment by JJSWART** [comment]
Hi mreram. 

I do not understand what is unfair? 

I added an extensive amount of features to the library and send a pull request to you? 

What do you mean by check them out? Please clarify so that I can make the corrections if needed. 

Kind Regards.

**Comment by mreram** [comment]
Hi JJSWART
Your features are very interesting.
I changed the different parts of your code. I said if you can review my changes and send pull request again(maybe you want to change a part).
Best Regards.

**Comment by JJSWART** [comment]
Hi mreram. 

Thanks, I will do that over the weekend. 

Have a good day.

**Comment by goghAta** [comment]
Please merge it.

**Comment by robdearpowa** [comment]
Can you please do something about this pull request?
It would be very usefull for me to use these new features

**Comment by mreram** [comment]
Sorry, 
I can't merge this pull request because there are many duplicate commits and issues.
I'll add these features later and I'll mention @JJSWART, but this pull request is open and @JJSWART can clean and review codes. thanks

**Pull request closed without merging**
